[[redirects]]
    from = "/discord"
    to = "https://discord.gg/bury"

    [[redirects]]
    from = "/*"
    to = "https://bury.lol"

    [[redirects]]
    from = "/s"
    to = "/s/index.html"
